// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO3OlC1RXHF3BI8-x1ApcocYGQAY0Z1UI',
    appId: '1:374467938493:web:20e29f548716d4a7c74fd4',
    messagingSenderId: '374467938493',
    projectId: 'naveensocailapp',
    authDomain: 'naveensocailapp.firebaseapp.com',
    storageBucket: 'naveensocailapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfyyS5-spQzR9c-yDyewRlUllER8LLht8',
    appId: '1:374467938493:android:5d4ac1737c2166fdc74fd4',
    messagingSenderId: '374467938493',
    projectId: 'naveensocailapp',
    storageBucket: 'naveensocailapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ1lXgUWxRF-TUn2HNWYtfGwtsLmNJv5A',
    appId: '1:374467938493:ios:107bd7d60be45310c74fd4',
    messagingSenderId: '374467938493',
    projectId: 'naveensocailapp',
    storageBucket: 'naveensocailapp.firebasestorage.app',
    iosBundleId: 'com.example.inter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ1lXgUWxRF-TUn2HNWYtfGwtsLmNJv5A',
    appId: '1:374467938493:ios:107bd7d60be45310c74fd4',
    messagingSenderId: '374467938493',
    projectId: 'naveensocailapp',
    storageBucket: 'naveensocailapp.firebasestorage.app',
    iosBundleId: 'com.example.inter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO3OlC1RXHF3BI8-x1ApcocYGQAY0Z1UI',
    appId: '1:374467938493:web:4b1cf68ce462cae6c74fd4',
    messagingSenderId: '374467938493',
    projectId: 'naveensocailapp',
    authDomain: 'naveensocailapp.firebaseapp.com',
    storageBucket: 'naveensocailapp.firebasestorage.app',
  );
}
